version: "3.8"

services:
 web:
    build:

      context: .

    container_name: "todo_container"


    ports:

      - "8000:8000"

#    volumes:
#
#      - ./app:/app

#    command: >
#
#      sh -c "python manage.py runserver 0.0.0.0:8000"