# Generated by Django 4.0 on 2022-01-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_todomodel_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='datecompleted',
            new_name='dateCompleted',
        ),
    ]
