# Generated by Django 4.0.1 on 2022-01-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_rename_datecompleted_todomodel_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='memo',
            new_name='description',
        ),
    ]
